version: 2.1

jobs:
  run_ray_example:
    docker:
      - image: gueraf/rules_ray_py_test:latest
    steps:
      - checkout
      - run:
          name: "Start ray cluster"
          command: ray start --head --disable-usage-stats
      - run:
          name: "Update local_path_override"
          command: |
            sed -i "s|./rules_ray_py|$(pwd)|g" /tmp/rules_ray_py_test/MODULE.bazel && \
            cat /tmp/rules_ray_py_test/MODULE.bazel
      - run:
          name: "examples/py_ray_hello_world:hello_world_ray_job"
          command: |
            cd /tmp/rules_ray_py_test/ && \
            bazelisk build examples/py_ray_hello_world:hello_world_ray_job && \
            timeout 2m bazelisk run examples/py_ray_hello_world:hello_world_ray_job -- --wait=true
      - run:
          name: "Wait for Ray cluster to be healthy"
          command: |
            echo "Waiting for Ray cluster to be healthy..."
            max_retries=30
            counter=0
            until ray status > /dev/null 2>&1; do
              counter=$((counter + 1))
              if [ $counter -eq $max_retries ]; then
                echo "Ray cluster failed to become healthy after $max_retries attempts."
                ray status  # Show the actual status before failing
                exit 1
              fi
              echo "Ray cluster not ready yet. Waiting (attempt $counter/$max_retries)..."
              sleep 2
            done
            echo "Ray cluster is healthy!"
      - run:
          name: "Collect Ray logs"
          command: |
            mkdir -p /tmp/ray_logs
            cp /tmp/ray/session_latest/logs/runtime_env_setup-*.log /tmp/ray_logs/ || echo "No runtime_env_setup logs found"
            cp /tmp/ray/session_latest/logs/runtime_env_agent.log /tmp/ray_logs/ || echo "No runtime_env_agent.log found"
          when: always # This ensures the step runs even if previous steps fail
      - store_artifacts:
          path: /tmp/ray_logs
          destination: ray-logs

workflows:
  version: 2
  main:
    jobs:
      - run_ray_example
