version: 2.1

jobs:
  run_ray_example:
    docker:
      - image: gueraf/rules_ray_py_test:latest
    steps:
      - checkout
      - run:
          name: "Start ray cluster"
          command: ray start --head --dashboard-host 0.0.0.0 --disable-usage-stats
      - run:
          name: "Update local_path_override"
          command: |
            sed -i "s|./rules_ray_py|$(pwd)|g" /tmp/rules_ray_py_test/MODULE.bazel && \
            cat /tmp/rules_ray_py_test/MODULE.bazel
      - run:
          name: "examples/py_ray_hello_world:hello_world_ray_job"
          command: |
            RAY_ADDRESS='http://127.0.0.1:8265' ray job submit -- /bin/bash -c 'pwd'

workflows:
  version: 2
  main:
    jobs:
      - run_ray_example
